import { ITheme } from "../types/ITheme";
import { Color, Depth, Spacing, Border, Font } from "@z11/shared-tokens";
import { IThemePalette } from "../types/IThemePalette";

const palette: IThemePalette = {
  accent: Color.indigo[60],
  accentDark: Color.indigo[70],
  accentDarker: Color.indigo[80],
  accentDarkest: Color.indigo[90],
  accentMidnight: Color.indigo[100],
  accentLight: Color.indigo[40],
  accentLighter: Color.indigo[30],
  accentLightest: Color.indigo[20],
  accentPastel: Color.indigo[10],
  black: Color.display.black,
  blue: Color.blue[60],
  blueDark: Color.blue[80],
  blueLight: Color.blue[10],
  green: Color.green[60],
  greenDark: Color.green[80],
  greenLight: Color.green[10],
  neutral: Color.gray[60],
  neutralDark: Color.gray[70],
  neutralDarker: Color.gray[80],
  neutralDarkest: Color.gray[90],
  neutralMidnight: Color.gray[100],
  neutralLight: Color.gray[40],
  neutralLighter: Color.gray[30],
  neutralLightest: Color.gray[20],
  neutralPastel: Color.gray[10],
  primary: Color.teal[60],
  primaryDark: Color.teal[70],
  primaryDarker: Color.teal[80],
  primaryDarkest: Color.teal[90],
  primaryMidnight: Color.teal[100],
  primaryLight: Color.teal[40],
  primaryLighter: Color.teal[30],
  primaryLightest: Color.teal[20],
  primaryPastel: Color.teal[10],
  red: Color.red[60],
  redDark: Color.red[80],
  redLight: Color.red[10],
  white: Color.display.white,
  yellow: Color.yellow[70],
  yellowDark: Color.yellow[90],
  yellowLight: Color.yellow[20],  
};

export const DefaultTheme: ITheme = {
  effect: {
    layer1: Depth[1],
    layer2: Depth[2],
    layer3: Depth[3],
    layer4: Depth[4],
    layer5: Depth[5],
    radius1: Border.radius[1],
    radius2: Border.radius[3],
    radius3: Border.radius[5],
  },
  font: {
    base: Font.family.sans,
    code: Font.family.mono,
    headings: Font.family.sans,
    labels: Font.family.sans,
    quotes: Font.family.serif,
  },
  palette,
  slot: {
    bg: palette.white,
    bgCatchy: palette.neutralPastel,
    bgChosen: palette.neutralLightest,
    bgFocused: palette.neutralLighter,
    border: palette.neutralLight,
    borderDisabled: palette.neutralLighter,
    buttonBg: palette.white,
    buttonBgActive: palette.neutralLightest,
    buttonBgDisabled: palette.neutralLightest,
    buttonBgFocused: palette.neutralLighter,
    buttonBorder: palette.neutral,
    buttonText: palette.neutralDarkest,
    buttonTextActive: palette.neutralDarker,
    buttonTextDisabled: palette.neutral,
    buttonTextFocused: palette.black,
    divider: palette.neutralLight,
    errorBg: palette.redLight,
    errorIcon: palette.redDark,
    errorText: palette.redDark,
    frame: palette.neutralLightest,
    infoBg: palette.blueLight,
    infoIcon: palette.blueDark,
    infoText: palette.blueDark,
    inputBg: palette.white,
    inputBgChosen: palette.neutralPastel,
    inputBgDisabled: palette.neutralLightest,
    inputBorder: palette.neutral,
    inputBorderChosen: palette.neutral,
    inputBorderDisabled: palette.neutral,
    inputBorderFocused: palette.neutralDarker,
    inputIcon: palette.neutralDark,
    inputIconDisabled: palette.neutral,
    inputIconFocused: palette.neutralDarker,
    inputText: palette.neutralDarkest,
    inputTextChosen: palette.neutralDarkest,
    inputTextDisabled: palette.neutral,
    link: palette.primary,
    linkFocused: palette.primaryDark,
    primaryButtonBg: palette.primary,
    primaryButtonBgActive: palette.primaryDarker,
    primaryButtonBgDisabled: palette.neutralLightest,
    primaryButtonBgFocused: palette.primaryDark,
    primaryButtonBorder: palette.primary,
    primaryButtonText: palette.white,
    primaryButtonTextActive: palette.white,
    primaryButtonTextDisabled: palette.white,
    primaryButtonTextFocused: palette.white,
    subtext:  palette.neutralDarker,
    subtextDisabled: palette.neutralDark,
    successBg: palette.greenLight,
    successIcon: palette.greenDark,
    successText: palette.greenDark,
    text: palette.neutralDarkest,
    textDisabled: palette.neutralDarker,
    warnBg: palette.yellowLight,
    warnIcon: palette.yellowDark,
    warnText: palette.yellowDark,
    buttonBorderActive: palette.neutralDarker,
    buttonBorderDisabled: palette.neutral,
    primaryButtonBorderActive: palette.primaryDarker,
    primaryButtonBorderDisabled: palette.neutral,
  },
  spacing: {
    lg: Spacing[5],
    md: Spacing[4],
    sm: Spacing[3],
    xs: Spacing[2],
    xl: Spacing[6],
    xxl: Spacing[7],
  },
};
