export const STYLE_BANNER = [
  '/**',
  ' * This file is automatically generated. Do NOT manually modify it.',
  ' * Create a new task or add additional exports to the variant manifest.',
  ' */',
  '',
];
