import { boxShadow, font, spacing, height, border } from "@z11/shared-tokens";
import { ISettings } from "./ITheme";

export const defaultSettings: ISettings = {  
  left: 'left',
  font: font.family.sansGhost,
  smallFontSize: font.baseSize.sm,
  baseFontSize: font.baseSize.md,
  lgFontSize: font.baseSize.lg,
  xlFontSize: font.baseSize.xl,
  xxlFontSize: font.baseSize.xxl,
  '3xlFontSize': font.baseSize['3xl'],
  '4xlFontSize': font.baseSize['4xl'],
  '5xlFontSize': font.baseSize['5xl'],
  headingFont: 'inherit',
  boldWeight: 600,
  strongWeight: 700,
  headingWeight: 100,
  leading: font.leading.normal,
  headingLeading: font.leading.normal,
  rhythm: spacing[2],
  focusBoxShadow: boxShadow.outline,
  responsiveFont: true,
  responsiveFontBreakpoint: '1.25vw',
  smallFontSizeLg: font.largeSize.sm,
  baseFontSizeLg: font.largeSize.md,
  lgFontSizeLg: font.largeSize.lg,
  xlFontSizeLg: font.largeSize.xl,
  xxlFontSizeLg: font.largeSize.xxl,
  '3xlFontSizeLg': font.largeSize['3xl'],
  '4xlFontSizeLg': font.largeSize['4xl'],
  '5xlFontSizeLg': font.largeSize['5xl'],
  dividerSize: height.px,
  listPadding: spacing[9],
  olCounter1: 'decimal',
  olCounter2: 'lower-alpha',
  olCounter3: 'lower-roman',
  olCounterSeparator: '"."',
  ulBullet1: '"\\2022"',
  ulBullet2: '"\\25E6"',
  ulBullet3: '"\\25AA"',
  ulBulletSpacing: spacing[2],
  monoFont: font.family.mono,
  roundedSm: border.radius.xs,
  roundedLg: border.radius.lg,
  roundedMd: border.radius.sm,
  monoBoldWeight: 600,
};
